/// Canonical registry for the requested platform surface. This avoids artificial
/// line-count inflation: each capability has a stable module boundary.
enum FeatureStatus { implemented, partial, planned }

class FeatureDescriptor {
  const FeatureDescriptor(
    this.id,
    this.group,
    this.description, {
    this.status = FeatureStatus.planned,
  });

  final String id;
  final String group;
  final String description;
  final FeatureStatus status;

  bool get implemented => status == FeatureStatus.implemented;
}
class FeatureRegistry {
  static const all = <FeatureDescriptor>[
    FeatureDescriptor('multi_tab','browser_core','Multiple independent browser tabs', status: FeatureStatus.implemented),
    FeatureDescriptor('tab_groups','browser_core','Named/color-coded tab groups'),
    FeatureDescriptor('private_tabs','browser_core','Private tab history/session exclusion; true cookie/cache/storage profile isolation requires native engine', status: FeatureStatus.partial),
    FeatureDescriptor('session_restore','browser_core','Restore previous sessions', status: FeatureStatus.partial),
    FeatureDescriptor('recently_closed','browser_core','Reopen recently closed tabs', status: FeatureStatus.implemented),
    FeatureDescriptor('back_forward','browser_core','Navigation history', status: FeatureStatus.implemented),
    FeatureDescriptor('reload_stop','browser_core','Reload and stop loading', status: FeatureStatus.implemented),
    FeatureDescriptor('user_agent','browser_core','Desktop/mobile user agent', status: FeatureStatus.implemented),
    FeatureDescriptor('zoom','browser_core','Per-tab zoom'),
    FeatureDescriptor('find_in_page','browser_core','Find text on page', status: FeatureStatus.implemented),
    FeatureDescriptor('translation','browser_core','Page translation boundary'),
    FeatureDescriptor('reader_mode','browser_core','Reader-mode presentation', status: FeatureStatus.implemented),
    FeatureDescriptor('fullscreen','browser_core','Fullscreen browsing'),
    FeatureDescriptor('picture_in_picture','browser_core','PiP integration boundary'),
    FeatureDescriptor('downloads','browser_core','Download manager boundary'),
    FeatureDescriptor('file_upload','browser_core','File upload support'),
    FeatureDescriptor('permissions','browser_core','Site permission policy'),
    FeatureDescriptor('popup_control','browser_core','Popup policy'),
    FeatureDescriptor('javascript_control','browser_core','JavaScript toggle', status: FeatureStatus.implemented),
    FeatureDescriptor('page_summary','ai','Summarize current page'),
    FeatureDescriptor('ask_page','ai','Ask questions about current page', status: FeatureStatus.partial),
    FeatureDescriptor('explain_selection','ai','Explain selected text'),
    FeatureDescriptor('rewrite','ai','Rewrite content'),
    FeatureDescriptor('ai_translate','ai','AI translation'),
    FeatureDescriptor('generate_content','ai','Generate content'),
    FeatureDescriptor('coding_assistant','ai','Coding assistant'),
    FeatureDescriptor('search_assistant','ai','Search-aware assistant'),
    FeatureDescriptor('ai_history','ai','Persist AI conversations'),
    FeatureDescriptor('conversation_folders','ai','Organize conversations'),
    FeatureDescriptor('streaming','ai','Streaming response boundary'),
    FeatureDescriptor('model_selection','ai','Selectable model/provider'),
    FeatureDescriptor('token_usage','ai','Token accounting'),
    FeatureDescriptor('context_management','ai','Context budgeting'),
    FeatureDescriptor('offline_ai','ai','Offline fallback', status: FeatureStatus.implemented),
    FeatureDescriptor('native_search','search','Native search result page', status: FeatureStatus.partial),
    FeatureDescriptor('suggestions','search','Search suggestions'),
    FeatureDescriptor('recent_searches','search','Recent query list'),
    FeatureDescriptor('search_history','search','Persistent search history'),
    FeatureDescriptor('categories','search','Search categories', status: FeatureStatus.implemented),
    FeatureDescriptor('images','search','Image results category', status: FeatureStatus.partial),
    FeatureDescriptor('news','search','News results category', status: FeatureStatus.partial),
    FeatureDescriptor('videos','search','Video results category', status: FeatureStatus.partial),
    FeatureDescriptor('shopping','search','Shopping results category', status: FeatureStatus.partial),
    FeatureDescriptor('safe_search','search','Safe-search policy'),
    FeatureDescriptor('region_language','search','Region/language selection'),
    FeatureDescriptor('search_abstraction','search','Provider-independent search API', status: FeatureStatus.implemented),
    FeatureDescriptor('tracker_blocking','privacy','Tracker blocking policy', status: FeatureStatus.partial),
    FeatureDescriptor('cookie_controls','privacy','Cookie controls', status: FeatureStatus.partial),
    FeatureDescriptor('third_party_cookies','privacy','Third-party cookie policy', status: FeatureStatus.partial),
    FeatureDescriptor('fingerprint_protection','privacy','Fingerprinting policy', status: FeatureStatus.partial),
    FeatureDescriptor('https_only','privacy','HTTPS-only navigation', status: FeatureStatus.partial),
    FeatureDescriptor('clear_data','privacy','Clear browsing data', status: FeatureStatus.implemented),
    FeatureDescriptor('site_permissions','privacy','Per-site permissions', status: FeatureStatus.partial),
    FeatureDescriptor('incognito','privacy','Private history/session exclusion; native profile isolation required for full incognito', status: FeatureStatus.partial),
    FeatureDescriptor('dns_configuration','privacy','DNS configuration boundary', status: FeatureStatus.partial),
    FeatureDescriptor('secure_dns','privacy','Secure DNS boundary', status: FeatureStatus.partial),
    FeatureDescriptor('privacy_dashboard','privacy','Privacy status dashboard', status: FeatureStatus.implemented),
    FeatureDescriptor('bookmarks','library','Bookmarks', status: FeatureStatus.implemented),
    FeatureDescriptor('bookmark_folders','library','Bookmark folders'),
    FeatureDescriptor('tags','library','Library tags'),
    FeatureDescriptor('reading_list','library','Reading list'),
    FeatureDescriptor('history','library','History', status: FeatureStatus.implemented),
    FeatureDescriptor('saved_pages','library','Saved pages'),
    FeatureDescriptor('notes','library','Notes', status: FeatureStatus.implemented),
    FeatureDescriptor('favorites','library','Favorites'),
    FeatureDescriptor('library_search','library','Search library', status: FeatureStatus.partial),
    FeatureDescriptor('library_import_export','library','Import/export library'),
    FeatureDescriptor('rich_text','notebook','Rich text note model boundary'),
    FeatureDescriptor('markdown','notebook','Markdown notes', status: FeatureStatus.implemented),
    FeatureDescriptor('notebook_folders','notebook','Notebook folders'),
    FeatureDescriptor('notebook_tags','notebook','Notebook tags'),
    FeatureDescriptor('notebook_search','notebook','Search notebook'),
    FeatureDescriptor('ai_summary_notes','notebook','AI note summary'),
    FeatureDescriptor('ai_rewrite_notes','notebook','AI note rewrite'),
    FeatureDescriptor('page_to_note','notebook','Save page to note'),
    FeatureDescriptor('highlight_to_note','notebook','Save highlights to note'),
    FeatureDescriptor('autosave','notebook','Autosave'),
    FeatureDescriptor('note_export','notebook','Export notes'),
    FeatureDescriptor('dynamic_theme','ui','Dynamic theme'),
    FeatureDescriptor('theme_modes','ui','Light/dark/system', status: FeatureStatus.implemented),
    FeatureDescriptor('amoled','ui','AMOLED dark mode'),
    FeatureDescriptor('accent_colors','ui','Accent customization'),
    FeatureDescriptor('custom_toolbar','ui','Custom browser toolbar'),
    FeatureDescriptor('animations','ui','Motion system'),
    FeatureDescriptor('glass_ui','ui','Glass visual surfaces'),
    FeatureDescriptor('responsive_layout','ui','Responsive layout', status: FeatureStatus.implemented),
    FeatureDescriptor('tablet_ui','ui','Tablet layout'),
    FeatureDescriptor('desktop_layout','ui','Desktop layout'),
    FeatureDescriptor('accessibility','ui','Accessibility'),
    FeatureDescriptor('font_scaling','ui','Font scaling'),
    FeatureDescriptor('gesture_navigation','ui','Gesture navigation'),
    FeatureDescriptor('api_gateway','backend','API gateway', status: FeatureStatus.implemented),
    FeatureDescriptor('ai_provider_abstraction','backend','AI provider abstraction', status: FeatureStatus.implemented),
    FeatureDescriptor('search_provider_abstraction','backend','Search provider abstraction', status: FeatureStatus.implemented),
    FeatureDescriptor('rate_limiting','backend','Rate limiting', status: FeatureStatus.implemented),
    FeatureDescriptor('request_validation','backend','Request validation', status: FeatureStatus.implemented),
    FeatureDescriptor('logging','backend','Structured logging boundary'),
    FeatureDescriptor('error_handling','backend','Central error handling', status: FeatureStatus.implemented),
    FeatureDescriptor('health_checks','backend','Health endpoints', status: FeatureStatus.implemented),
    FeatureDescriptor('configuration','backend','Environment configuration', status: FeatureStatus.implemented),
    FeatureDescriptor('secure_secrets','backend','Secrets kept server-side', status: FeatureStatus.implemented),
    FeatureDescriptor('caching','backend','Response caching boundary'),
    FeatureDescriptor('retry_policy','backend','Bounded retry policy'),
    FeatureDescriptor('malicious_url_protection','security','Malicious URL policy', status: FeatureStatus.implemented),
    FeatureDescriptor('javascript_scheme_block','security','Block javascript scheme', status: FeatureStatus.implemented),
    FeatureDescriptor('data_scheme_policy','security','Restrict data scheme', status: FeatureStatus.implemented),
    FeatureDescriptor('file_scheme_policy','security','Restrict file scheme', status: FeatureStatus.implemented),
    FeatureDescriptor('redirect_validation','security','Validate redirects', status: FeatureStatus.implemented),
    FeatureDescriptor('phishing_warning','security','Suspicious-domain warning boundary'),
    FeatureDescriptor('download_url_validation','security','Validate download URLs'),
    FeatureDescriptor('external_intent_policy','security','Control external intents'),
    FeatureDescriptor('ssl_error_handling','security','Navigation/SSL error handling', status: FeatureStatus.implemented),
  ];
}
